"""
phantom-protocol — post-quantum-secure L4/L6 transport SDK.

This package is generated by maturin (uniffi bindings mode). The native
library (libphantom_protocol.{so,dylib,dll}) is bundled inside the wheel and
loaded automatically when you import this package.

All public symbols (PhantomSession, PhantomListener, connect_pinned, etc.) are
re-exported from the generated uniffi module below.

Quick start::

    from phantom_protocol import connect_pinned, PhantomListener

See https://docs.rs/phantom-protocol for the full API reference.
"""

# The uniffi-generated module is placed in the same package directory by
# maturin. It loads the bundled cdylib via ctypes on import.
from .phantom_protocol import *  # noqa: F401, F403
from .phantom_protocol import __all__ as _all  # noqa: F401

# Re-export the uniffi __all__ list so `from phantom_protocol import *` works.
try:
    __all__ = _all  # type: ignore[name-defined]
except NameError:
    # Fallback: uniffi-generated module does not define __all__ in all
    # versions — that is fine, the star-import still works.
    pass
