// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(phantom_coreFFI)
import phantom_coreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_phantom_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_phantom_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsurePhantomCoreInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDuration: FfiConverterRustBuffer {
    typealias SwiftType = TimeInterval

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TimeInterval {
        let seconds: UInt64 = try readInt(&buf)
        let nanoseconds: UInt32 = try readInt(&buf)
        return Double(seconds) + (Double(nanoseconds) / 1.0e9)
    }

    public static func write(_ value: TimeInterval, into buf: inout [UInt8]) {
        if value.rounded(.down) > Double(Int64.max) {
            fatalError("Duration overflow, exceeds max bounds supported by Uniffi")
        }

        if value < 0 {
            fatalError("Invalid duration, must be non-negative")
        }

        let seconds = UInt64(value)
        let nanoseconds = UInt32((value - Double(seconds)) * 1.0e9)
        writeInt(&buf, seconds)
        writeInt(&buf, nanoseconds)
    }
}




/**
 * Outcome of a successful [`PhantomListener::accept`] — the accepted
 * session plus any 0-RTT early-data the client carried on its V3
 * ClientHello (wire V3, Phase 4.1).
 *
 * A `uniffi::Object` rather than a record: it returns an
 * `Arc<PhantomSession>` (itself a `uniffi::Object`) from a method,
 * the same known-good pattern `accept()` used before V3. `take_*`
 * is take-once so a ≤16 KiB blob is moved out, not cloned.
 */
public protocol AcceptOutcomeProtocol: AnyObject, Sendable {
    
    /**
     * Whether 0-RTT early-data is present and not yet taken.
     */
    func hasEarlyData()  -> Bool
    
    /**
     * The accepted, fully-established session.
     */
    func session()  -> PhantomSession
    
    /**
     * Take the 0-RTT early-data the client sent on its ClientHello.
     * Take-once — a second call returns `None`. `None` also means the
     * client sent no early-data, or the server rejected it (unknown /
     * expired ticket, oversized blob, AEAD failure).
     */
    func takeEarlyData()  -> Data?
    
}
/**
 * Outcome of a successful [`PhantomListener::accept`] — the accepted
 * session plus any 0-RTT early-data the client carried on its V3
 * ClientHello (wire V3, Phase 4.1).
 *
 * A `uniffi::Object` rather than a record: it returns an
 * `Arc<PhantomSession>` (itself a `uniffi::Object`) from a method,
 * the same known-good pattern `accept()` used before V3. `take_*`
 * is take-once so a ≤16 KiB blob is moved out, not cloned.
 */
open class AcceptOutcome: AcceptOutcomeProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_phantom_core_fn_clone_acceptoutcome(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_phantom_core_fn_free_acceptoutcome(pointer, $0) }
    }

    

    
    /**
     * Whether 0-RTT early-data is present and not yet taken.
     */
open func hasEarlyData() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_phantom_core_fn_method_acceptoutcome_has_early_data(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * The accepted, fully-established session.
     */
open func session() -> PhantomSession  {
    return try!  FfiConverterTypePhantomSession_lift(try! rustCall() {
    uniffi_phantom_core_fn_method_acceptoutcome_session(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Take the 0-RTT early-data the client sent on its ClientHello.
     * Take-once — a second call returns `None`. `None` also means the
     * client sent no early-data, or the server rejected it (unknown /
     * expired ticket, oversized blob, AEAD failure).
     */
open func takeEarlyData() -> Data?  {
    return try!  FfiConverterOptionData.lift(try! rustCall() {
    uniffi_phantom_core_fn_method_acceptoutcome_take_early_data(self.uniffiClonePointer(),$0
    )
})
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAcceptOutcome: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = AcceptOutcome

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> AcceptOutcome {
        return AcceptOutcome(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: AcceptOutcome) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AcceptOutcome {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: AcceptOutcome, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAcceptOutcome_lift(_ pointer: UnsafeMutableRawPointer) throws -> AcceptOutcome {
    return try FfiConverterTypeAcceptOutcome.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAcceptOutcome_lower(_ value: AcceptOutcome) -> UnsafeMutableRawPointer {
    return FfiConverterTypeAcceptOutcome.lower(value)
}






public protocol PhantomListenerProtocol: AnyObject, Sendable {
    
    /**
     * Accept the next inbound connection and complete its handshake.
     *
     * Returns an [`AcceptOutcome`] — the established session plus any
     * 0-RTT early-data the client carried on a V3 ClientHello. Use
     * `.session()` for the session and `.take_early_data()` for the
     * early-data (the latter is `None` for a plain V1/V2 handshake or
     * when the server rejected the early-data).
     */
    func accept() async throws  -> AcceptOutcome
    
    /**
     * Whether `shutdown()` has been called.
     */
    func isShuttingDown()  -> Bool
    
    /**
     * Local socket address the listener is actually bound to (resolved at
     * bind time). Useful when the caller passed `"host:0"` and needs to
     * learn which port the OS assigned.
     */
    func localAddr()  -> String
    
    /**
     * Signal graceful shutdown (Phase 4.6).
     *
     * Sets the `shutting_down` flag and wakes any `accept()` call currently
     * parked on the listener so it can unwind with
     * `CoreError::ConnectionClosed`. Idempotent — calling more than once is
     * safe. Already-accepted sessions are NOT affected; they continue
     * serving until their owning task closes them.
     */
    func shutdown() 
    
    /**
     * The server's long-lived hybrid verifying key, serialized via
     * `HybridVerifyingKey::to_bytes`. Clients MUST pin this value before
     * completing a handshake to defeat MITM (see Vuln 1 in security review).
     */
    func verifyingKeyBytes()  -> Data
    
}
open class PhantomListener: PhantomListenerProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_phantom_core_fn_clone_phantomlistener(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_phantom_core_fn_free_phantomlistener(pointer, $0) }
    }

    
public static func bind(addr: String)async throws  -> PhantomListener  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_phantom_core_fn_constructor_phantomlistener_bind(FfiConverterString.lower(addr)
                )
            },
            pollFunc: ffi_phantom_core_rust_future_poll_pointer,
            completeFunc: ffi_phantom_core_rust_future_complete_pointer,
            freeFunc: ffi_phantom_core_rust_future_free_pointer,
            liftFunc: FfiConverterTypePhantomListener_lift,
            errorHandler: FfiConverterTypeCoreError_lift
        )
}
    

    
    /**
     * Accept the next inbound connection and complete its handshake.
     *
     * Returns an [`AcceptOutcome`] — the established session plus any
     * 0-RTT early-data the client carried on a V3 ClientHello. Use
     * `.session()` for the session and `.take_early_data()` for the
     * early-data (the latter is `None` for a plain V1/V2 handshake or
     * when the server rejected the early-data).
     */
open func accept()async throws  -> AcceptOutcome  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_phantom_core_fn_method_phantomlistener_accept(
                    self.uniffiClonePointer()
                    
                )
            },
            pollFunc: ffi_phantom_core_rust_future_poll_pointer,
            completeFunc: ffi_phantom_core_rust_future_complete_pointer,
            freeFunc: ffi_phantom_core_rust_future_free_pointer,
            liftFunc: FfiConverterTypeAcceptOutcome_lift,
            errorHandler: FfiConverterTypeCoreError_lift
        )
}
    
    /**
     * Whether `shutdown()` has been called.
     */
open func isShuttingDown() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_phantom_core_fn_method_phantomlistener_is_shutting_down(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Local socket address the listener is actually bound to (resolved at
     * bind time). Useful when the caller passed `"host:0"` and needs to
     * learn which port the OS assigned.
     */
open func localAddr() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_phantom_core_fn_method_phantomlistener_local_addr(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Signal graceful shutdown (Phase 4.6).
     *
     * Sets the `shutting_down` flag and wakes any `accept()` call currently
     * parked on the listener so it can unwind with
     * `CoreError::ConnectionClosed`. Idempotent — calling more than once is
     * safe. Already-accepted sessions are NOT affected; they continue
     * serving until their owning task closes them.
     */
open func shutdown()  {try! rustCall() {
    uniffi_phantom_core_fn_method_phantomlistener_shutdown(self.uniffiClonePointer(),$0
    )
}
}
    
    /**
     * The server's long-lived hybrid verifying key, serialized via
     * `HybridVerifyingKey::to_bytes`. Clients MUST pin this value before
     * completing a handshake to defeat MITM (see Vuln 1 in security review).
     */
open func verifyingKeyBytes() -> Data  {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_phantom_core_fn_method_phantomlistener_verifying_key_bytes(self.uniffiClonePointer(),$0
    )
})
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePhantomListener: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = PhantomListener

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> PhantomListener {
        return PhantomListener(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: PhantomListener) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PhantomListener {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: PhantomListener, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePhantomListener_lift(_ pointer: UnsafeMutableRawPointer) throws -> PhantomListener {
    return try FfiConverterTypePhantomListener.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePhantomListener_lower(_ value: PhantomListener) -> UnsafeMutableRawPointer {
    return FfiConverterTypePhantomListener.lower(value)
}






/**
 * Client-first session — instant `connect()`, non-blocking `send()`.
 *
 * # Design
 *
 * ```text
 * let session = PhantomSession::connect("server:443");  // instant!
 * session.send(data).await;   // queued until handshake completes
 * session.send(data2).await;  // also queued
 * // ... handshake completes in background ...
 * // queued data auto-flushed, new sends go directly
 * ```
 *
 * The session progresses through states:
 * `Connecting → ClassicalReady → PqcUpgrading → PqcReady → Connected`
 */
public protocol PhantomSessionProtocol: AnyObject, Sendable {
    
    /**
     * Get the current connection state (lock-free).
     */
    func connectionState()  -> ConnectionState
    
    /**
     * Send the graceful close frame and shut the session down.
     *
     * Named `disconnect` rather than `close` because UniFFI's Kotlin
     * generator unconditionally adds `AutoCloseable.close()` to every
     * object, and a Rust-side `close` here would conflict with it.
     */
    func disconnect() async throws 
    
    /**
     * The 0-RTT verdict for this session.
     *
     * - `None` — still handshaking, the handshake failed, or the client sent
     * no early-data on this connect.
     * - `Some(true)` — the server consumed the 0-RTT early-data.
     * - `Some(false)` — the client sent early-data and the server rejected it
     * (stale/unknown ticket, oversized blob, or AEAD failure). The caller
     * must re-send that payload over the normal channel.
     */
    func earlyDataAccepted() async  -> Bool?
    
    /**
     * Flush all queued messages (called when handshake completes).
     */
    func flushQueue() async throws  -> UInt32
    
    /**
     * Session identifier.
     */
    func id()  -> String
    
    /**
     * Whether the session is ready for data transmission.
     */
    func isDataReady()  -> Bool
    
    /**
     * Whether the session has full PQC protection.
     */
    func isPqcReady()  -> Bool
    
    /**
     * Open a new multiplexed stream
     */
    func openStream()  -> PhantomStream
    
    /**
     * Target peer address.
     */
    func peerAddr()  -> String
    
    /**
     * Number of messages queued (waiting for handshake).
     */
    func queuedCount() async  -> UInt32
    
    /**
     * Receive data from the session.
     *
     * Internally the recv pipeline keeps payloads as `Bytes` to avoid the
     * per-packet Vec clone that used to fan out to the stream demux. The
     * FFI surface still hands callers a `Vec<u8>`; if this is the last
     * refcount the Vec is moved out of the underlying buffer, otherwise
     * `Bytes::to_vec` copies.
     */
    func recv() async throws  -> Data
    
    /**
     * Extract a [`ResumptionHint`] for a future 0-RTT reconnect.
     *
     * Returns `Some` after a successful handshake; `None` while still
     * handshaking, after a failure, or before the inner session has
     * been published.
     *
     * Store the hint alongside the pinned `HybridVerifyingKey` of the
     * server it was negotiated against and feed it back to
     * [`connect_pinned_with_resumption`]. Reusing a hint across
     * servers is a configuration bug — the `resumption_secret` is
     * server-pinned.
     */
    func resumptionHint() async  -> ResumptionHint?
    
    /**
     * Send data through the session.
     *
     * - If the session is connected: sends immediately
     * - If still handshaking: queues the data for auto-flush later
     */
    func send(data: Data) async throws 
    
}
/**
 * Client-first session — instant `connect()`, non-blocking `send()`.
 *
 * # Design
 *
 * ```text
 * let session = PhantomSession::connect("server:443");  // instant!
 * session.send(data).await;   // queued until handshake completes
 * session.send(data2).await;  // also queued
 * // ... handshake completes in background ...
 * // queued data auto-flushed, new sends go directly
 * ```
 *
 * The session progresses through states:
 * `Connecting → ClassicalReady → PqcUpgrading → PqcReady → Connected`
 */
open class PhantomSession: PhantomSessionProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_phantom_core_fn_clone_phantomsession(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_phantom_core_fn_free_phantomsession(pointer, $0) }
    }

    
    /**
     * Create a new session — returns instantly.
     *
     * Handshake is not started until a transport is provided.
     * Use `connect_with_transport()` for full integration.
     */
public static func connect(peerAddr: String) -> PhantomSession  {
    return try!  FfiConverterTypePhantomSession_lift(try! rustCall() {
    uniffi_phantom_core_fn_constructor_phantomsession_connect(
        FfiConverterString.lower(peerAddr),$0
    )
})
}
    

    
    /**
     * Get the current connection state (lock-free).
     */
open func connectionState() -> ConnectionState  {
    return try!  FfiConverterTypeConnectionState_lift(try! rustCall() {
    uniffi_phantom_core_fn_method_phantomsession_connection_state(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Send the graceful close frame and shut the session down.
     *
     * Named `disconnect` rather than `close` because UniFFI's Kotlin
     * generator unconditionally adds `AutoCloseable.close()` to every
     * object, and a Rust-side `close` here would conflict with it.
     */
open func disconnect()async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_phantom_core_fn_method_phantomsession_disconnect(
                    self.uniffiClonePointer()
                    
                )
            },
            pollFunc: ffi_phantom_core_rust_future_poll_void,
            completeFunc: ffi_phantom_core_rust_future_complete_void,
            freeFunc: ffi_phantom_core_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeCoreError_lift
        )
}
    
    /**
     * The 0-RTT verdict for this session.
     *
     * - `None` — still handshaking, the handshake failed, or the client sent
     * no early-data on this connect.
     * - `Some(true)` — the server consumed the 0-RTT early-data.
     * - `Some(false)` — the client sent early-data and the server rejected it
     * (stale/unknown ticket, oversized blob, or AEAD failure). The caller
     * must re-send that payload over the normal channel.
     */
open func earlyDataAccepted()async  -> Bool?  {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_phantom_core_fn_method_phantomsession_early_data_accepted(
                    self.uniffiClonePointer()
                    
                )
            },
            pollFunc: ffi_phantom_core_rust_future_poll_rust_buffer,
            completeFunc: ffi_phantom_core_rust_future_complete_rust_buffer,
            freeFunc: ffi_phantom_core_rust_future_free_rust_buffer,
            liftFunc: FfiConverterOptionBool.lift,
            errorHandler: nil
            
        )
}
    
    /**
     * Flush all queued messages (called when handshake completes).
     */
open func flushQueue()async throws  -> UInt32  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_phantom_core_fn_method_phantomsession_flush_queue(
                    self.uniffiClonePointer()
                    
                )
            },
            pollFunc: ffi_phantom_core_rust_future_poll_u32,
            completeFunc: ffi_phantom_core_rust_future_complete_u32,
            freeFunc: ffi_phantom_core_rust_future_free_u32,
            liftFunc: FfiConverterUInt32.lift,
            errorHandler: FfiConverterTypeCoreError_lift
        )
}
    
    /**
     * Session identifier.
     */
open func id() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_phantom_core_fn_method_phantomsession_id(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Whether the session is ready for data transmission.
     */
open func isDataReady() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_phantom_core_fn_method_phantomsession_is_data_ready(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Whether the session has full PQC protection.
     */
open func isPqcReady() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_phantom_core_fn_method_phantomsession_is_pqc_ready(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Open a new multiplexed stream
     */
open func openStream() -> PhantomStream  {
    return try!  FfiConverterTypePhantomStream_lift(try! rustCall() {
    uniffi_phantom_core_fn_method_phantomsession_open_stream(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Target peer address.
     */
open func peerAddr() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_phantom_core_fn_method_phantomsession_peer_addr(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Number of messages queued (waiting for handshake).
     */
open func queuedCount()async  -> UInt32  {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_phantom_core_fn_method_phantomsession_queued_count(
                    self.uniffiClonePointer()
                    
                )
            },
            pollFunc: ffi_phantom_core_rust_future_poll_u32,
            completeFunc: ffi_phantom_core_rust_future_complete_u32,
            freeFunc: ffi_phantom_core_rust_future_free_u32,
            liftFunc: FfiConverterUInt32.lift,
            errorHandler: nil
            
        )
}
    
    /**
     * Receive data from the session.
     *
     * Internally the recv pipeline keeps payloads as `Bytes` to avoid the
     * per-packet Vec clone that used to fan out to the stream demux. The
     * FFI surface still hands callers a `Vec<u8>`; if this is the last
     * refcount the Vec is moved out of the underlying buffer, otherwise
     * `Bytes::to_vec` copies.
     */
open func recv()async throws  -> Data  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_phantom_core_fn_method_phantomsession_recv(
                    self.uniffiClonePointer()
                    
                )
            },
            pollFunc: ffi_phantom_core_rust_future_poll_rust_buffer,
            completeFunc: ffi_phantom_core_rust_future_complete_rust_buffer,
            freeFunc: ffi_phantom_core_rust_future_free_rust_buffer,
            liftFunc: FfiConverterData.lift,
            errorHandler: FfiConverterTypeCoreError_lift
        )
}
    
    /**
     * Extract a [`ResumptionHint`] for a future 0-RTT reconnect.
     *
     * Returns `Some` after a successful handshake; `None` while still
     * handshaking, after a failure, or before the inner session has
     * been published.
     *
     * Store the hint alongside the pinned `HybridVerifyingKey` of the
     * server it was negotiated against and feed it back to
     * [`connect_pinned_with_resumption`]. Reusing a hint across
     * servers is a configuration bug — the `resumption_secret` is
     * server-pinned.
     */
open func resumptionHint()async  -> ResumptionHint?  {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_phantom_core_fn_method_phantomsession_resumption_hint(
                    self.uniffiClonePointer()
                    
                )
            },
            pollFunc: ffi_phantom_core_rust_future_poll_rust_buffer,
            completeFunc: ffi_phantom_core_rust_future_complete_rust_buffer,
            freeFunc: ffi_phantom_core_rust_future_free_rust_buffer,
            liftFunc: FfiConverterOptionTypeResumptionHint.lift,
            errorHandler: nil
            
        )
}
    
    /**
     * Send data through the session.
     *
     * - If the session is connected: sends immediately
     * - If still handshaking: queues the data for auto-flush later
     */
open func send(data: Data)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_phantom_core_fn_method_phantomsession_send(
                    self.uniffiClonePointer(),
                    FfiConverterData.lower(data)
                )
            },
            pollFunc: ffi_phantom_core_rust_future_poll_void,
            completeFunc: ffi_phantom_core_rust_future_complete_void,
            freeFunc: ffi_phantom_core_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeCoreError_lift
        )
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePhantomSession: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = PhantomSession

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> PhantomSession {
        return PhantomSession(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: PhantomSession) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PhantomSession {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: PhantomSession, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePhantomSession_lift(_ pointer: UnsafeMutableRawPointer) throws -> PhantomSession {
    return try FfiConverterTypePhantomSession.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePhantomSession_lower(_ value: PhantomSession) -> UnsafeMutableRawPointer {
    return FfiConverterTypePhantomSession.lower(value)
}






public protocol PhantomStreamProtocol: AnyObject, Sendable {
    
    /**
     * Close this stream; the peer will see EOF on its read half.
     *
     * Named `disconnect` rather than `close` for the same reason as
     * `PhantomSession::disconnect` — UniFFI's Kotlin generator emits
     * `AutoCloseable.close()` on every object.
     */
    func disconnect() async throws 
    
    func recv() async throws  -> Data
    
    func sendReliable(data: Data) async throws 
    
    func sendUnreliable(data: Data) async throws 
    
    func streamId()  -> UInt32
    
}
open class PhantomStream: PhantomStreamProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_phantom_core_fn_clone_phantomstream(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_phantom_core_fn_free_phantomstream(pointer, $0) }
    }

    

    
    /**
     * Close this stream; the peer will see EOF on its read half.
     *
     * Named `disconnect` rather than `close` for the same reason as
     * `PhantomSession::disconnect` — UniFFI's Kotlin generator emits
     * `AutoCloseable.close()` on every object.
     */
open func disconnect()async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_phantom_core_fn_method_phantomstream_disconnect(
                    self.uniffiClonePointer()
                    
                )
            },
            pollFunc: ffi_phantom_core_rust_future_poll_void,
            completeFunc: ffi_phantom_core_rust_future_complete_void,
            freeFunc: ffi_phantom_core_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeCoreError_lift
        )
}
    
open func recv()async throws  -> Data  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_phantom_core_fn_method_phantomstream_recv(
                    self.uniffiClonePointer()
                    
                )
            },
            pollFunc: ffi_phantom_core_rust_future_poll_rust_buffer,
            completeFunc: ffi_phantom_core_rust_future_complete_rust_buffer,
            freeFunc: ffi_phantom_core_rust_future_free_rust_buffer,
            liftFunc: FfiConverterData.lift,
            errorHandler: FfiConverterTypeCoreError_lift
        )
}
    
open func sendReliable(data: Data)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_phantom_core_fn_method_phantomstream_send_reliable(
                    self.uniffiClonePointer(),
                    FfiConverterData.lower(data)
                )
            },
            pollFunc: ffi_phantom_core_rust_future_poll_void,
            completeFunc: ffi_phantom_core_rust_future_complete_void,
            freeFunc: ffi_phantom_core_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeCoreError_lift
        )
}
    
open func sendUnreliable(data: Data)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_phantom_core_fn_method_phantomstream_send_unreliable(
                    self.uniffiClonePointer(),
                    FfiConverterData.lower(data)
                )
            },
            pollFunc: ffi_phantom_core_rust_future_poll_void,
            completeFunc: ffi_phantom_core_rust_future_complete_void,
            freeFunc: ffi_phantom_core_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeCoreError_lift
        )
}
    
open func streamId() -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_phantom_core_fn_method_phantomstream_stream_id(self.uniffiClonePointer(),$0
    )
})
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePhantomStream: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = PhantomStream

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> PhantomStream {
        return PhantomStream(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: PhantomStream) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PhantomStream {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: PhantomStream, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePhantomStream_lift(_ pointer: UnsafeMutableRawPointer) throws -> PhantomStream {
    return try FfiConverterTypePhantomStream.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePhantomStream_lower(_ value: PhantomStream) -> UnsafeMutableRawPointer {
    return FfiConverterTypePhantomStream.lower(value)
}




public struct PhantomConfig {
    /**
     * Interval between keep-alive pings
     */
    public var keepaliveInterval: TimeInterval
    /**
     * Session inactivity timeout
     */
    public var sessionTimeout: TimeInterval
    /**
     * Maximum packet size (MTU)
     */
    public var maxPacketSize: UInt32
    /**
     * Send buffer size in packets
     */
    public var sendBufferSize: UInt32
    /**
     * Receive buffer size in packets
     */
    public var recvBufferSize: UInt32
    /**
     * Maximum tickets in session cache
     */
    public var sessionCacheCapacity: UInt32
    /**
     * Lifetime of a session ticket
     */
    public var sessionTicketLifetime: TimeInterval
    /**
     * Enable automatic transport fallback
     */
    public var autoFallback: Bool
    /**
     * Packet loss percentage to trigger fallback
     */
    public var fallbackLossThreshold: UInt8
    /**
     * Connection failures to trigger fallback
     */
    public var fallbackFailureThreshold: UInt32
    /**
     * Timeout for connection attempts
     */
    public var connectTimeout: TimeInterval
    /**
     * Delay before attempting to upgrade transport
     */
    public var upgradeDelay: TimeInterval

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Interval between keep-alive pings
         */keepaliveInterval: TimeInterval, 
        /**
         * Session inactivity timeout
         */sessionTimeout: TimeInterval, 
        /**
         * Maximum packet size (MTU)
         */maxPacketSize: UInt32, 
        /**
         * Send buffer size in packets
         */sendBufferSize: UInt32, 
        /**
         * Receive buffer size in packets
         */recvBufferSize: UInt32, 
        /**
         * Maximum tickets in session cache
         */sessionCacheCapacity: UInt32, 
        /**
         * Lifetime of a session ticket
         */sessionTicketLifetime: TimeInterval, 
        /**
         * Enable automatic transport fallback
         */autoFallback: Bool, 
        /**
         * Packet loss percentage to trigger fallback
         */fallbackLossThreshold: UInt8, 
        /**
         * Connection failures to trigger fallback
         */fallbackFailureThreshold: UInt32, 
        /**
         * Timeout for connection attempts
         */connectTimeout: TimeInterval, 
        /**
         * Delay before attempting to upgrade transport
         */upgradeDelay: TimeInterval) {
        self.keepaliveInterval = keepaliveInterval
        self.sessionTimeout = sessionTimeout
        self.maxPacketSize = maxPacketSize
        self.sendBufferSize = sendBufferSize
        self.recvBufferSize = recvBufferSize
        self.sessionCacheCapacity = sessionCacheCapacity
        self.sessionTicketLifetime = sessionTicketLifetime
        self.autoFallback = autoFallback
        self.fallbackLossThreshold = fallbackLossThreshold
        self.fallbackFailureThreshold = fallbackFailureThreshold
        self.connectTimeout = connectTimeout
        self.upgradeDelay = upgradeDelay
    }
}

#if compiler(>=6)
extension PhantomConfig: Sendable {}
#endif


extension PhantomConfig: Equatable, Hashable {
    public static func ==(lhs: PhantomConfig, rhs: PhantomConfig) -> Bool {
        if lhs.keepaliveInterval != rhs.keepaliveInterval {
            return false
        }
        if lhs.sessionTimeout != rhs.sessionTimeout {
            return false
        }
        if lhs.maxPacketSize != rhs.maxPacketSize {
            return false
        }
        if lhs.sendBufferSize != rhs.sendBufferSize {
            return false
        }
        if lhs.recvBufferSize != rhs.recvBufferSize {
            return false
        }
        if lhs.sessionCacheCapacity != rhs.sessionCacheCapacity {
            return false
        }
        if lhs.sessionTicketLifetime != rhs.sessionTicketLifetime {
            return false
        }
        if lhs.autoFallback != rhs.autoFallback {
            return false
        }
        if lhs.fallbackLossThreshold != rhs.fallbackLossThreshold {
            return false
        }
        if lhs.fallbackFailureThreshold != rhs.fallbackFailureThreshold {
            return false
        }
        if lhs.connectTimeout != rhs.connectTimeout {
            return false
        }
        if lhs.upgradeDelay != rhs.upgradeDelay {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(keepaliveInterval)
        hasher.combine(sessionTimeout)
        hasher.combine(maxPacketSize)
        hasher.combine(sendBufferSize)
        hasher.combine(recvBufferSize)
        hasher.combine(sessionCacheCapacity)
        hasher.combine(sessionTicketLifetime)
        hasher.combine(autoFallback)
        hasher.combine(fallbackLossThreshold)
        hasher.combine(fallbackFailureThreshold)
        hasher.combine(connectTimeout)
        hasher.combine(upgradeDelay)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePhantomConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PhantomConfig {
        return
            try PhantomConfig(
                keepaliveInterval: FfiConverterDuration.read(from: &buf), 
                sessionTimeout: FfiConverterDuration.read(from: &buf), 
                maxPacketSize: FfiConverterUInt32.read(from: &buf), 
                sendBufferSize: FfiConverterUInt32.read(from: &buf), 
                recvBufferSize: FfiConverterUInt32.read(from: &buf), 
                sessionCacheCapacity: FfiConverterUInt32.read(from: &buf), 
                sessionTicketLifetime: FfiConverterDuration.read(from: &buf), 
                autoFallback: FfiConverterBool.read(from: &buf), 
                fallbackLossThreshold: FfiConverterUInt8.read(from: &buf), 
                fallbackFailureThreshold: FfiConverterUInt32.read(from: &buf), 
                connectTimeout: FfiConverterDuration.read(from: &buf), 
                upgradeDelay: FfiConverterDuration.read(from: &buf)
        )
    }

    public static func write(_ value: PhantomConfig, into buf: inout [UInt8]) {
        FfiConverterDuration.write(value.keepaliveInterval, into: &buf)
        FfiConverterDuration.write(value.sessionTimeout, into: &buf)
        FfiConverterUInt32.write(value.maxPacketSize, into: &buf)
        FfiConverterUInt32.write(value.sendBufferSize, into: &buf)
        FfiConverterUInt32.write(value.recvBufferSize, into: &buf)
        FfiConverterUInt32.write(value.sessionCacheCapacity, into: &buf)
        FfiConverterDuration.write(value.sessionTicketLifetime, into: &buf)
        FfiConverterBool.write(value.autoFallback, into: &buf)
        FfiConverterUInt8.write(value.fallbackLossThreshold, into: &buf)
        FfiConverterUInt32.write(value.fallbackFailureThreshold, into: &buf)
        FfiConverterDuration.write(value.connectTimeout, into: &buf)
        FfiConverterDuration.write(value.upgradeDelay, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePhantomConfig_lift(_ buf: RustBuffer) throws -> PhantomConfig {
    return try FfiConverterTypePhantomConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePhantomConfig_lower(_ value: PhantomConfig) -> RustBuffer {
    return FfiConverterTypePhantomConfig.lower(value)
}


/**
 * 0-RTT resumption material extracted from a completed session.
 *
 * Produced by [`PhantomSession::resumption_hint`] after a handshake
 * completes, and fed back into [`connect_pinned_with_resumption`] to
 * attempt a 0-RTT reconnect to the same server.
 *
 * Both fields are exactly 32 bytes — this record is the
 * UniFFI-representable surface for the internal `(session_id,
 * resumption_secret)` tuple. The fields are `Vec<u8>` because UniFFI
 * has no fixed-size-array type, so the length is a runtime invariant
 * checked when the hint is used.
 *
 * Store the hint alongside the pinned `HybridVerifyingKey` of the
 * server it was negotiated against: the `resumption_secret` is
 * server-pinned, and reusing a hint across servers is a configuration
 * bug.
 */
public struct ResumptionHint {
    /**
     * The negotiated session id (32 bytes).
     */
    public var sessionId: Data
    /**
     * The resumption secret (32 bytes) — sensitive; treat like a key.
     */
    public var resumptionSecret: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * The negotiated session id (32 bytes).
         */sessionId: Data, 
        /**
         * The resumption secret (32 bytes) — sensitive; treat like a key.
         */resumptionSecret: Data) {
        self.sessionId = sessionId
        self.resumptionSecret = resumptionSecret
    }
}

#if compiler(>=6)
extension ResumptionHint: Sendable {}
#endif


extension ResumptionHint: Equatable, Hashable {
    public static func ==(lhs: ResumptionHint, rhs: ResumptionHint) -> Bool {
        if lhs.sessionId != rhs.sessionId {
            return false
        }
        if lhs.resumptionSecret != rhs.resumptionSecret {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(sessionId)
        hasher.combine(resumptionSecret)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeResumptionHint: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ResumptionHint {
        return
            try ResumptionHint(
                sessionId: FfiConverterData.read(from: &buf), 
                resumptionSecret: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: ResumptionHint, into buf: inout [UInt8]) {
        FfiConverterData.write(value.sessionId, into: &buf)
        FfiConverterData.write(value.resumptionSecret, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeResumptionHint_lift(_ buf: RustBuffer) throws -> ResumptionHint {
    return try FfiConverterTypeResumptionHint.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeResumptionHint_lower(_ value: ResumptionHint) -> RustBuffer {
    return FfiConverterTypeResumptionHint.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Connection state for `PhantomSession`.
 *
 * The session is usable from the moment it's created — sends are queued
 * until the handshake completes.
 */

public enum ConnectionState : UInt8 {
    
    /**
     * Connection initiated, handshake pending
     */
    case connecting = 0
    /**
     * Classical (X25519) channel established — data flows
     */
    case classicalReady = 1
    /**
     * PQC upgrade in progress
     */
    case pqcUpgrading = 2
    /**
     * Full hybrid PQC protection active
     */
    case pqcReady = 3
    /**
     * Fully connected and operational
     */
    case connected = 4
    /**
     * Connection failed
     */
    case failed = 5
    /**
     * Gracefully closed
     */
    case closed = 6
}


#if compiler(>=6)
extension ConnectionState: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeConnectionState: FfiConverterRustBuffer {
    typealias SwiftType = ConnectionState

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ConnectionState {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .connecting
        
        case 2: return .classicalReady
        
        case 3: return .pqcUpgrading
        
        case 4: return .pqcReady
        
        case 5: return .connected
        
        case 6: return .failed
        
        case 7: return .closed
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ConnectionState, into buf: inout [UInt8]) {
        switch value {
        
        
        case .connecting:
            writeInt(&buf, Int32(1))
        
        
        case .classicalReady:
            writeInt(&buf, Int32(2))
        
        
        case .pqcUpgrading:
            writeInt(&buf, Int32(3))
        
        
        case .pqcReady:
            writeInt(&buf, Int32(4))
        
        
        case .connected:
            writeInt(&buf, Int32(5))
        
        
        case .failed:
            writeInt(&buf, Int32(6))
        
        
        case .closed:
            writeInt(&buf, Int32(7))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConnectionState_lift(_ buf: RustBuffer) throws -> ConnectionState {
    return try FfiConverterTypeConnectionState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConnectionState_lower(_ value: ConnectionState) -> RustBuffer {
    return FfiConverterTypeConnectionState.lower(value)
}


extension ConnectionState: Equatable, Hashable {}







/**
 * Universal Core Error Enum compatible with FFI exports
 */
public enum CoreError: Swift.Error {

    
    
    case NetworkError(String
    )
    case SerializationError(String
    )
    case Busy
    case ConfigError(String
    )
    case CryptoError(String
    )
    case ValidationError(String
    )
    case RuntimeError(String
    )
    case KeyDerivationError
    case RngError(String
    )
    case InternalError(String
    )
    case HandshakeError(String
    )
    case StreamError(String
    )
    case SessionNotFound(String
    )
    case ConnectionClosed
    case Timeout
    /**
     * Sliding-window replay protection rejected a packet. The AEAD layer
     * already cryptographically prevents replay (strict-counter nonces), but
     * the explicit window catches duplicates earlier and gives operators a
     * metric signal (`replay_rejected_total`).
     */
    case ReplayDetected(String
    )
    /**
     * A requested cipher suite is not available in the current build.
     * Emitted under `--features fips` when a caller asks for a
     * non-FIPS-approved primitive (today: `ChaCha20-Poly1305`). The
     * variant is always compiled so error matching stays stable across
     * feature configurations.
     */
    case CipherSuiteUnavailable(String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCoreError: FfiConverterRustBuffer {
    typealias SwiftType = CoreError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CoreError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .NetworkError(
            try FfiConverterString.read(from: &buf)
            )
        case 2: return .SerializationError(
            try FfiConverterString.read(from: &buf)
            )
        case 3: return .Busy
        case 4: return .ConfigError(
            try FfiConverterString.read(from: &buf)
            )
        case 5: return .CryptoError(
            try FfiConverterString.read(from: &buf)
            )
        case 6: return .ValidationError(
            try FfiConverterString.read(from: &buf)
            )
        case 7: return .RuntimeError(
            try FfiConverterString.read(from: &buf)
            )
        case 8: return .KeyDerivationError
        case 9: return .RngError(
            try FfiConverterString.read(from: &buf)
            )
        case 10: return .InternalError(
            try FfiConverterString.read(from: &buf)
            )
        case 11: return .HandshakeError(
            try FfiConverterString.read(from: &buf)
            )
        case 12: return .StreamError(
            try FfiConverterString.read(from: &buf)
            )
        case 13: return .SessionNotFound(
            try FfiConverterString.read(from: &buf)
            )
        case 14: return .ConnectionClosed
        case 15: return .Timeout
        case 16: return .ReplayDetected(
            try FfiConverterString.read(from: &buf)
            )
        case 17: return .CipherSuiteUnavailable(
            try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CoreError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .NetworkError(v1):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .SerializationError(v1):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(v1, into: &buf)
            
        
        case .Busy:
            writeInt(&buf, Int32(3))
        
        
        case let .ConfigError(v1):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .CryptoError(v1):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .ValidationError(v1):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .RuntimeError(v1):
            writeInt(&buf, Int32(7))
            FfiConverterString.write(v1, into: &buf)
            
        
        case .KeyDerivationError:
            writeInt(&buf, Int32(8))
        
        
        case let .RngError(v1):
            writeInt(&buf, Int32(9))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .InternalError(v1):
            writeInt(&buf, Int32(10))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .HandshakeError(v1):
            writeInt(&buf, Int32(11))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .StreamError(v1):
            writeInt(&buf, Int32(12))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .SessionNotFound(v1):
            writeInt(&buf, Int32(13))
            FfiConverterString.write(v1, into: &buf)
            
        
        case .ConnectionClosed:
            writeInt(&buf, Int32(14))
        
        
        case .Timeout:
            writeInt(&buf, Int32(15))
        
        
        case let .ReplayDetected(v1):
            writeInt(&buf, Int32(16))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .CipherSuiteUnavailable(v1):
            writeInt(&buf, Int32(17))
            FfiConverterString.write(v1, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCoreError_lift(_ buf: RustBuffer) throws -> CoreError {
    return try FfiConverterTypeCoreError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCoreError_lower(_ value: CoreError) -> RustBuffer {
    return FfiConverterTypeCoreError.lower(value)
}


extension CoreError: Equatable, Hashable {}




extension CoreError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionBool: FfiConverterRustBuffer {
    typealias SwiftType = Bool?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterBool.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterBool.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionData: FfiConverterRustBuffer {
    typealias SwiftType = Data?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterData.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterData.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeResumptionHint: FfiConverterRustBuffer {
    typealias SwiftType = ResumptionHint?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeResumptionHint.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeResumptionHint.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_MAYBE_READY: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call the ensure init function since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsurePhantomCoreInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                uniffiFutureContinuationCallback,
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}
public func connectPinned(host: String, port: UInt16, pinnedKey: Data)async throws  -> PhantomSession  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_phantom_core_fn_func_connect_pinned(FfiConverterString.lower(host),FfiConverterUInt16.lower(port),FfiConverterData.lower(pinnedKey)
                )
            },
            pollFunc: ffi_phantom_core_rust_future_poll_pointer,
            completeFunc: ffi_phantom_core_rust_future_complete_pointer,
            freeFunc: ffi_phantom_core_rust_future_free_pointer,
            liftFunc: FfiConverterTypePhantomSession_lift,
            errorHandler: FfiConverterTypeCoreError_lift
        )
}
/**
 * Connect to a pinned server with a **0-RTT resumption attempt** — the
 * resumption-aware analogue of [`connect_pinned`].
 *
 * `hint` is a [`ResumptionHint`] from a prior session's
 * [`PhantomSession::resumption_hint`]; both of its fields must be
 * exactly 32 bytes or the call fails with `ValidationError` before any
 * socket is opened. `early_data` (≤ 16 KiB) is sealed into the resuming
 * ClientHello so it reaches the server on the very first flight.
 *
 * Acceptance is best-effort: when the server does not consume the early-data
 * (stale/unknown ticket or AEAD failure) the handshake completes 1-RTT — the
 * caller checks [`PhantomSession::early_data_accepted`] and re-sends over the
 * normal channel when it is not `Some(true)`.
 *
 * Native-only, like [`connect_pinned`]: `TcpSessionTransport` lives
 * behind `cfg(not(target_arch = "wasm32"))`.
 */
public func connectPinnedWithResumption(host: String, port: UInt16, pinnedKey: Data, hint: ResumptionHint, earlyData: Data)async throws  -> PhantomSession  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_phantom_core_fn_func_connect_pinned_with_resumption(FfiConverterString.lower(host),FfiConverterUInt16.lower(port),FfiConverterData.lower(pinnedKey),FfiConverterTypeResumptionHint_lower(hint),FfiConverterData.lower(earlyData)
                )
            },
            pollFunc: ffi_phantom_core_rust_future_poll_pointer,
            completeFunc: ffi_phantom_core_rust_future_complete_pointer,
            freeFunc: ffi_phantom_core_rust_future_free_pointer,
            liftFunc: FfiConverterTypePhantomSession_lift,
            errorHandler: FfiConverterTypeCoreError_lift
        )
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_phantom_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_phantom_core_checksum_func_connect_pinned() != 59015) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_phantom_core_checksum_func_connect_pinned_with_resumption() != 47866) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_phantom_core_checksum_method_acceptoutcome_has_early_data() != 16642) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_phantom_core_checksum_method_acceptoutcome_session() != 49660) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_phantom_core_checksum_method_acceptoutcome_take_early_data() != 486) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_phantom_core_checksum_method_phantomlistener_accept() != 39902) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_phantom_core_checksum_method_phantomlistener_is_shutting_down() != 2657) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_phantom_core_checksum_method_phantomlistener_local_addr() != 18579) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_phantom_core_checksum_method_phantomlistener_shutdown() != 32103) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_phantom_core_checksum_method_phantomlistener_verifying_key_bytes() != 27980) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_phantom_core_checksum_method_phantomsession_connection_state() != 58300) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_phantom_core_checksum_method_phantomsession_disconnect() != 18611) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_phantom_core_checksum_method_phantomsession_early_data_accepted() != 3077) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_phantom_core_checksum_method_phantomsession_flush_queue() != 41158) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_phantom_core_checksum_method_phantomsession_id() != 60002) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_phantom_core_checksum_method_phantomsession_is_data_ready() != 43904) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_phantom_core_checksum_method_phantomsession_is_pqc_ready() != 25634) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_phantom_core_checksum_method_phantomsession_open_stream() != 23478) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_phantom_core_checksum_method_phantomsession_peer_addr() != 2094) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_phantom_core_checksum_method_phantomsession_queued_count() != 9183) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_phantom_core_checksum_method_phantomsession_recv() != 61516) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_phantom_core_checksum_method_phantomsession_resumption_hint() != 18816) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_phantom_core_checksum_method_phantomsession_send() != 35674) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_phantom_core_checksum_method_phantomstream_disconnect() != 13449) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_phantom_core_checksum_method_phantomstream_recv() != 59636) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_phantom_core_checksum_method_phantomstream_send_reliable() != 49428) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_phantom_core_checksum_method_phantomstream_send_unreliable() != 4743) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_phantom_core_checksum_method_phantomstream_stream_id() != 4640) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_phantom_core_checksum_constructor_phantomlistener_bind() != 5086) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_phantom_core_checksum_constructor_phantomsession_connect() != 9656) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsurePhantomCoreInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all