use phantom_core::network::framing::Framer;
use phantom_core::network::control::ControlMessage;
use phantom_core::network::serialization::{serialize, deserialize};
use tokio::net::TcpStream;
use tokio::io::{AsyncReadExt, AsyncWriteExt};
use std::error::Error;


#[tokio::test]
async fn test_ds_flow() -> Result<(), Box<dyn Error>> {
    // 1. Connect (TLS skipped for raw test or using TlsConnector if server enforces it? Server enforces TLS.)
    // We need TLS. Let's rely on the fact that we can use `phantom_core::network::tls` to config client.
    
    // For simplicity, let's assume we can run this test against the running server.
    // We need to implement the TLS handshake logic here or reuse `PhantomClient` internals? 
    // `PhantomClient` is opaque.
    // Let's copy-paste the connection logic for the test.
    
    let addr = "127.0.0.1:3001";
    println!("Connecting to {}...", addr);
    
    // START TLS SETUP
    let mut root_store = rustls::RootCertStore::empty();
    // In test mode, we might need a custom root or rely on system.
    // But `run_test.py` used pinning. Here we can use `dangerous_configuration`? No, we removed it.
    // We must load `server.crt` generated by the server.
    
    // Load existing cert (generated by server at workspace root)
    let cert_path = if std::path::Path::new("server.crt").exists() {
        "server.crt"
    } else {
        "../server.crt"
    };
    
    let cert_pem = std::fs::read_to_string(cert_path).expect("Failed to read server.crt");
    let mut reader = std::io::BufReader::new(cert_pem.as_bytes());
    let certs = rustls_pemfile::certs(&mut reader)?;
    for cert in certs {
        root_store.add(&rustls::Certificate(cert))?;
    }
    
    let config = rustls::ClientConfig::builder()
        .with_safe_defaults()
        .with_root_certificates(root_store)
        .with_no_client_auth();
    let connector = tokio_rustls::TlsConnector::from(std::sync::Arc::new(config));
    let domain = rustls::ServerName::try_from("localhost").unwrap();
    
    let stream = TcpStream::connect(addr).await?;
    let mut stream = connector.connect(domain, stream).await?;
    // END TLS SETUP
    
    println!("Connected over TLS!");
    
    // 2. Prepare Control Message (Register)
    use openmls::prelude::*;
    use phantom_core::crypto::provider::{QuantumProvider, QuantumSigner};
    use openmls_traits::crypto::OpenMlsCrypto;
    use tls_codec::Serialize as TlsSerialize;

    let provider = QuantumProvider::default();
    
    // 2a. Generate Signature Keypair
    let (sk, pk) = provider.signature_key_gen(SignatureScheme::ED25519)
        .expect("SigGen");
        
    // 2b. Identity
    let identity = blake3::hash(&pk).as_bytes().to_vec();
    
    // 2c. Credential
    let credential = Credential::new(identity.clone(), CredentialType::Basic)
        .expect("Cred");
        
    // 2d. Signer
    let signer = QuantumSigner::new(provider.clone(), sk.clone(), SignatureScheme::ED25519);
    
    // 2e. KeyPackage
    let ciphersuite = Ciphersuite::MLS_128_DHKEMX25519_CHACHA20POLY1305_SHA256_Ed25519; 
    let config = CryptoConfig::with_default_version(ciphersuite);
    let backend = provider.clone();
     
    let credential_with_key = CredentialWithKey {
         credential,
         signature_key: pk.clone().into(),
    };
    
    let key_package = KeyPackage::builder()
         .key_package_extensions(Extensions::empty())
         .build(config, &backend, &signer, credential_with_key)
         .expect("Build KP");
         
    let key_package_bytes = key_package.tls_serialize_detached().expect("Ser KP");
    
    // 2f. Sign Request (ControlMessage signature)
    let mut msg_to_sign = Vec::new();
    msg_to_sign.extend_from_slice(&identity);
    msg_to_sign.extend_from_slice(&key_package_bytes);
    
    let signature = provider.sign(SignatureScheme::ED25519, &msg_to_sign, &sk)
        .expect("Sign");

    let register_msg = ControlMessage::Register { 
        identity: identity.clone(),
        key_package: key_package_bytes.clone(),
        signature,
        verifying_key: pk,
    };
    
    let payload = serialize(&register_msg)?;
    let zero_group = [0u8; 16];
    
    // Send Frame (Auth Token empty for now)
    // Send Frame (Auth Token empty for now)
    Framer::write_frame(&mut stream, &zero_group, 0, &payload, &[]).await?;
    stream.flush().await?;
    println!("Sending Register...");
    
    // 3. Prepare Control Message (Fetch)
    let fetch_msg = ControlMessage::FetchKeyPackage { identity: identity.clone() };
    let fetch_payload = serialize(&fetch_msg)?;
    
    Framer::write_frame(&mut stream, &zero_group, 0, &fetch_payload, &[]).await?;
    stream.flush().await?;
    println!("Sending Fetch...");
    
    // 4. Read Response
    println!("Waiting for response...");
    let (gid, _, resp_payload, _) = Framer::read_frame(&mut stream).await?;
    
    assert_eq!(gid, zero_group);
    
    // Force alignment
    let resp_payload_aligned = resp_payload.to_vec();
    
    let resp: ControlMessage = deserialize(&resp_payload_aligned)?;
    
    match resp {
        ControlMessage::KeyPackageResponse { key_package: Some(ref kp) } => {
            println!("Success! Received KeyPackage ({} bytes)", kp.len());
            assert_eq!(kp, &key_package_bytes);
        }
        _ => panic!("Unexpected response: {:?}", resp),
    }

    Ok(())
}
